# Generated by Django 4.0 on 2022-04-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
