# Generated by Django 4.0 on 2022-04-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_room_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
