# Generated by Django 4.0 on 2022-04-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_video_remove_room_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
