# Generated by Django 4.0 on 2022-04-10 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_video_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='caption',
        ),
        migrations.AddField(
            model_name='video',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.room'),
        ),
    ]
