# Generated by Django 4.0 on 2022-04-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_remove_video_caption_video_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='room_id',
        ),
        migrations.AddField(
            model_name='video',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
