# Generated by Django 4.0 on 2022-04-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_remove_video_room_id_video_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='caption',
        ),
    ]
